fix(announce): Fixes links, mentions and hashtags for Bluesky.#1611
jreleaser/jreleaser pull request #1645
Opened 2024-04-30 21:22 UTC by TomCools

Fixes #1611

### Context
Fixes broken hyperlinks, mentions and hashtags.

I have tagged the Jreleaser Bluesky account in some test posts, so you can verify it works.

### Checklist
- [ ] [Review Contribution Guidelines](https://github.com/jreleaser/jreleaser/blob/master/CONTRIBUTING.adoc).
- [ ] Make sure all contributed code can be distributed under the terms of the 
      [Apache License 2.0](https://github.com/jreleaser/jreleaser/blob/master/LICENSE), e.g. the code was written by 
      you or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Update [documentation](https://github.com/jreleaser/jreleaser.github.io) when applicable.

2024-04-30 21:32 UTC, TomCools commented
The BlueskyStringEncodingWrapper was inspired by the following answer on SO: https://stackoverflow.com/a/58553748. Checking with you @aalmiray, should we attribute this persons answer in the codebase?

2024-04-30 21:42 UTC, aalmiray commented on sdks/jreleaser-bluesky-java-sdk/src/main/java/org/jreleaser/sdk/bluesky/BlueskyRecordFactory.java
> +    private static final Pattern TAG_PATTERN = Pattern.compile("(#[a-zA-z]{2,})");
@TomCools looks like this should be `a-zA-Z` (capitalized Z)

2024-04-30 21:47 UTC, aalmiray requested changes
A regex needs update

2024-04-30 21:47 UTC, aalmiray commented
We would have to verify the code is his own first 🤷‍♂️

2024-05-01 07:14 UTC, TomCools commented
I was inspired by his code.. but the idea to "implement a new class of CharSequence and pass that to Matcher for regex matching" only can have so much variations.

I don't think checking his code ownership is feasible... how do we proceed from here? (Releasing 1.12 without this fix is an option ofc)

2024-05-01 07:58 UTC, merged