feat(announce): Add discourse sdk
jreleaser/jreleaser pull request #990
Opened 2022-10-24 12:28 UTC by shblue21

Fixes #?

### Context

I added the Discourse SDK and added it to Announce.
Discourse is an OpenSource-based forum and is used in many development forums (Twitter, Samsung, etc.)

I followed the keywords in the [API](http://docs.discourse.org) document as much as possible.

Thank you.

### Checklist
- [x] [Review Contribution Guidelines](https://github.com/jreleaser/jreleaser/blob/master/CONTRIBUTING.adoc).
- [x] Make sure all contributed code can be distributed under the terms of the 
      [Apache License 2.0](https://github.com/jreleaser/jreleaser/blob/master/LICENSE), e.g. the code was written by 
      you or the original code is licensed under [a license compatible to Apache License 2.0](https://apache.org/legal/resolved.html).
- [ ] Update [documentation](https://github.com/jreleaser/jreleaser.github.io) when applicable.

2022-10-24 12:30 UTC, shblue21 commented
If you want to actually test, use the host and API key below (it doesn't matter if the key is exposed as it's a development server)

URL : http://discourse-jihun.kro.kr/
Api-Username : jreleaser
Api-Key : 480e3fbde1dc1eed612c3226e7c1883dfbc00d385a819406a9e12c7adb574936

2022-10-24 12:44 UTC, aalmiray reviewed
Thank you so much for this PR! However, the gradle plugin also requires an update as this plugin has its own model that's mapped to core.

2022-10-24 12:44 UTC, aalmiray commented on core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/announce/DiscourseAnnouncerValidator.java
> +            discourse.setMessageTemplate("src/jreleaser/templates/discussions.tpl");
I suppose this string could be replaced with the constant `DEFAULT_DISCOURSE_TPL`

2022-10-24 12:44 UTC, aalmiray commented on sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/api/Category.java
> +    public ArrayList<Object> subcategory_ids;
These two collections could be `List<>` instead of `ArrayList<>`

2022-10-24 12:44 UTC, aalmiray commented on sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/api/CategoryList.java
> +    public ArrayList<Category> categories;
could be `List<>` instead

2022-10-24 12:44 UTC, aalmiray commented on sdks/jreleaser-discourse-java-sdk/src/main/java/org/jreleaser/sdk/discourse/api/Post.java
> +    public ArrayList<ActionsSummary> actions_summary;
could be `List<>` instead

2022-10-24 12:44 UTC, aalmiray commented on sdks/jreleaser-discourse-java-sdk/src/test/java/org/jreleaser/sdk/discourse/DiscoursePostTest.java
> +import static com.github.tomakehurst.wiremock.client.WireMock.*;
Please use explicit imports instead of * imports

2022-10-24 12:44 UTC, aalmiray commented on sdks/jreleaser-discourse-java-sdk/src/test/java/org/jreleaser/sdk/discourse/Stubs.java
> +import static com.github.tomakehurst.wiremock.client.WireMock.*;
please use explicit imports instead of * imports

2022-10-25 09:49 UTC, shblue21 commented
@aalmiray Thanks for the code review. I use jreleaser well for my work.

2022-10-25 17:53 UTC, aalmiray requested changes
Thank you. Latest updates look good. We're still missing the Gradle DSL updates in `plugins/jreleaser-gradle-plugin`.

2022-10-26 14:25 UTC, merged

2022-10-26 14:25 UTC, aalmiray commented
Thank you!

2022-10-27 00:58 UTC, shblue21 commented
Oh sorry for the late reply. Thanks for merging. Can I add it to the docs? (jrelaser.github.io)

2022-10-27 09:00 UTC, aalmiray commented
Don't worry about the docs, I've already added the relevant info 😉